### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by renanrdmachado** [renanrdmachado/conecta#1]
- [ ] Users
	- [ ] columns (id,name,nicename,email,password,status,user_type,active,complete,token)

- [ ] Usermeta
	- [ ] columns (id,user_id,meta_key,meta_value)
	
- [ ] Posts
	- [ ] columns (id,post_author,post_type,post_title,post_content,url,status,active,complete)

- [ ] Postmeta
	- [ ] columns (id,post_id,meta_key,meta_value)

- [ ] Posts_relations
	- [ ] columns (id,post_source,user_source,post_related,user_related,status)

- [ ] Options
	- [ ] columns (id,key,value,location)

- [ ] Notifications
	- [ ] columns ()
- [ ] Medias
- [ ] Logs
